# Generated by Django 3.1.4 on 2021-01-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='production_type',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('p_type', models.CharField(max_length=50, verbose_name='Типа')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='sport_type',
            fields=[
                ('id_sport_type', models.AutoField(primary_key=True, serialize=False)),
                ('sport_type', models.CharField(max_length=50, verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.TextField(verbose_name='Информация')),
                ('about', models.TextField(verbose_name='Обо мне')),
                ('upkeep', models.TextField(verbose_name='Уход')),
                ('size_and_cut', models.TextField(null=True, verbose_name='Размер и крой')),
                ('keep', models.TextField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('P', 'Portion')], verbose_name='Уход')),
                ('brend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория')),
                ('production_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.production_type', verbose_name='Тип продукта')),
                ('sport_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sport_type', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
