# Generated by Django 3.1.4 on 2021-01-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('brand_ru', models.CharField(max_length=50, null=True, verbose_name='Бренд')),
                ('brand_en', models.CharField(max_length=50, null=True, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, verbose_name='Категории')),
                ('category_ru', models.CharField(max_length=50, null=True, verbose_name='Категории')),
                ('category_en', models.CharField(max_length=50, null=True, verbose_name='Категории')),
                ('url', models.CharField(default='url', max_length=50, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='sport_type',
            fields=[
                ('id_sport_type', models.AutoField(primary_key=True, serialize=False)),
                ('sport_type', models.CharField(max_length=50, verbose_name='Вид спорта')),
                ('sport_type_ru', models.CharField(max_length=50, null=True, verbose_name='Вид спорта')),
                ('sport_type_en', models.CharField(max_length=50, null=True, verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='production_type',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('p_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('p_type_ru', models.CharField(max_length=50, null=True, verbose_name='Тип')),
                ('p_type_en', models.CharField(max_length=50, null=True, verbose_name='Тип')),
                ('people', models.TextField(choices=[('m', 'Male'), ('f', 'Female'), ('c', 'Child')], default='All', verbose_name='Люди')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='type/', verbose_name='Изображения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50, verbose_name='Название')),
                ('prod_name_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('prod_name_en', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('info', models.TextField(verbose_name='Информация')),
                ('info_ru', models.TextField(null=True, verbose_name='Информация')),
                ('info_en', models.TextField(null=True, verbose_name='Информация')),
                ('about', models.TextField(verbose_name='Обо мне')),
                ('about_ru', models.TextField(null=True, verbose_name='Обо мне')),
                ('about_en', models.TextField(null=True, verbose_name='Обо мне')),
                ('upkeep', models.TextField(verbose_name='Уход')),
                ('upkeep_ru', models.TextField(null=True, verbose_name='Уход')),
                ('upkeep_en', models.TextField(null=True, verbose_name='Уход')),
                ('size_and_cut', models.TextField(null=True, verbose_name='Размер и крой')),
                ('size_and_cut_ru', models.TextField(null=True, verbose_name='Размер и крой')),
                ('size_and_cut_en', models.TextField(null=True, verbose_name='Размер и крой')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Бренд')),
                ('brand_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Бренд')),
                ('brand_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Бренд')),
                ('production_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.production_type', verbose_name='Тип продукта')),
                ('production_type_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.production_type', verbose_name='Тип продукта')),
                ('production_type_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.production_type', verbose_name='Тип продукта')),
                ('sport_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sport_type', verbose_name='Вид спорта')),
                ('sport_type_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sport_type', verbose_name='Вид спорта')),
                ('sport_type_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sport_type', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
