# Generated by Django 3.1.4 on 2021-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_type',
            name='url',
            field=models.CharField(default='url', max_length=50, verbose_name='URL'),
        ),
    ]
