# Generated by Django 3.1.4 on 2021-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_production_type_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sport_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sport_type_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='prod/', verbose_name='Изображения'),
        ),
    ]
