# Generated by Django 3.1.4 on 2021-01-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210114_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_ru',
        ),
    ]
