# Generated by Django 3.1.4 on 2021-01-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210121_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prod/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.production_type', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_and_cut',
            field=models.TextField(blank=True, null=True, verbose_name='Размер и крой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_and_cut_en',
            field=models.TextField(blank=True, null=True, verbose_name='Размер и крой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_and_cut_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Размер и крой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.sport_type', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='production_type',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='production_type',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='production_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='type/', verbose_name='Изображения'),
        ),
    ]
