# Generated by Django 3.1.4 on 2021-01-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210115_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Категории'),
        ),
    ]
