# Generated by Django 3.1.4 on 2021-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210115_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='category',
            name='people',
            field=models.TextField(choices=[('a', 'All'), ('m', 'Male'), ('f', 'Female'), ('c', 'Child')], default='All', verbose_name='Люди'),
        ),
    ]
