# Generated by Django 3.1.4 on 2021-01-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210118_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='people',
        ),
        migrations.AddField(
            model_name='production_type',
            name='people',
            field=models.TextField(choices=[('a', 'All'), ('m', 'Male'), ('f', 'Female'), ('c', 'Child')], default='All', verbose_name='Люди'),
        ),
    ]
