# Generated by Django 3.1.4 on 2021-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210118_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_type',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
