# Generated by Django 3.1.4 on 2021-01-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_production_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default='url', max_length=50, verbose_name='URL'),
        ),
    ]
