# Generated by Django 3.1.4 on 2021-01-28 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_save_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_basket',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
