# Generated by Django 3.1.4 on 2021-01-28 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20210128_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.TextField(choices=[('D', 'Delivery'), ('P', 'Pick-up service')], verbose_name='Метод доставки')),
                ('strit', models.TextField(blank=True, null=True, verbose_name='Улица')),
                ('house', models.TextField(blank=True, null=True, verbose_name='Дом')),
                ('housing', models.IntegerField(blank=True, null=True, verbose_name='Корпус')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('entrance', models.IntegerField(blank=True, null=True, verbose_name='Подъезд')),
                ('tel', models.TextField(blank=True, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
