# Generated by Django 3.1.4 on 2021-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(default='0', verbose_name='Цена'),
        ),
    ]
