# Generated by Django 3.1.4 on 2021-03-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210129_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prod/', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='production_type',
            name='people',
            field=models.TextField(choices=[('m', 'Male'), ('f', 'Female')], default='All', verbose_name='Люди'),
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prod_img/', verbose_name='Загрузить изображение')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
            },
        ),
    ]
